back_description: "Se téléporter à l'endroit de votre dernière mort"
heal_descritpion: "Se soigner"
feed_description: "Se nourrir"

back_success: "§aVous avez été téléporté à votre dernière mort avec succès."
feed_success: "§aVous avez été nourris avec succès."
heal_success: "§aVous avez été soigné avec succès."

back_notfound: "§cVous n'avez aucune mort récente."
not_permission: "§cVous n'avez pas la permission d'utiliser cette commande."
not_player: "Cette commande n'est pas utilisable par la console."